---
- name: Installer les dépendances
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Ajouter le référentiel Docker GPG
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ajouter le référentiel Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Installer Docker
  apt:
    name: docker-ce
    state: present

- name: Démarrer et activer le service Docker
  service:
    name: docker
    state: started
    enabled: yes
